name: Host - Node

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-tokens
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - job_id: "thr1.AAAAAGkDxwrVCRy3_hZTTA.k64he044OFk"
            index: 0
          - job_id: "thr1.AAAAAGkDxxPEmYioQOH4Yg.mx4_UeVQhxQ"
            index: 1
          - job_id: "thr1.AAAAAGkDxxm_MUgQX3tBIg.Ka_BjhIA_lo"
            index: 2
          - job_id: "thr1.AAAAAGkDxyBRU7oG907x1g.dtaLWHarhY0"
            index: 3
          - job_id: "thr1.AAAAAGkDxyatsnRmAkTxPw.VoiltYV_TSU"
            index: 4
          - job_id: "thr1.AAAAAGkDxy3pa-zCQwQbOA.U5DnknzatFM"
            index: 5
          - job_id: "thr1.AAAAAGkDxzPH_T-9Fg3Eow.RDnwlMaljoo"
            index: 6
          - job_id: "thr1.AAAAAGkDxz42QCrIORp2yw.Mb_naISxmcU"
            index: 7
          - job_id: "thr1.AAAAAGkDx0dr7LmYTi6OCw.0IHzEil1F2k"
            index: 8
          - job_id: "thr1.AAAAAGkDx1ECNH36XT76Ig.MFx95fCZh58"
            index: 9
          - job_id: "thr1.AAAAAGkDx1--qlEcx0WJ7A.E4LbCreLPmA"
            index: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: |
          npm install

      - name: Esperar inicio sincronizado
        run: sleep 10

      - name: Ejecutar script
        run: node hosts.js
        env:
          JOB_ID: ${{ matrix.job_id }}
          INDEX: ${{ matrix.index }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "ðŸ‘½"
