name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGkTxsBy-k-NEerNdQ.4-EgmkXxZaU"
            index: 0
          - recaptcha_token: "thr1.AAAAAGkTxsmtVEOJzGRBKg.W8oDUleXh1M"
            index: 1
          - recaptcha_token: "thr1.AAAAAGkTxtA5koXujhVhuA.iH_hM-0KwcM"
            index: 2
          - recaptcha_token: "thr1.AAAAAGkTxtYue6gfbaEn7A.Mi7DSp5CU70"
            index: 3
          - recaptcha_token: "thr1.AAAAAGkTxttByNNJa0aBfg.heXv_3MzQaY"
            index: 4
          - recaptcha_token: "thr1.AAAAAGkTxuOrnspz92GWTQ.b_-om2PenJI"
            index: 5
          - recaptcha_token: "thr1.AAAAAGkTxukHINe0tBWoBg.N6-N-re1zn0"
            index: 6
          - recaptcha_token: "thr1.AAAAAGkTxvMDdZJWHSduIQ.ls4LYWQNSPo"
            index: 7
          - recaptcha_token: "thr1.AAAAAGkTxwCckMtfwblDwA.k-Yuw2XGTgA"
            index: 8
          - recaptcha_token: "thr1.AAAAAGkTxwiO0lKflg_D4w.0XH3MYZ6yus"
            index: 9
          - recaptcha_token: "thr1.AAAAAGkTxxGcmR--V3RSsA.ijMxwSO6F8k"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: ‚è≥ Esperar inicio sincronizado
        run: sleep 10

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
