name: Host - Node

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-tokens
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
         - job_id: "thr1.AAAAAGkTg9m4Ff11zcG2pQ.-wv3RYFqnEs"
           index: 0
         - job_id: "thr1.AAAAAGkTg98fiQQC6Lg-2g.eGbsYtwxUYs"
           index: 1
         - job_id: "thr1.AAAAAGkTg-WVVlR-Zr99Aw.v8Uiw1INrPc"
           index: 2
         - job_id: "thr1.AAAAAGkTg-vPB78Zd7CdWA.sSLrbygGZPo"
           index: 3
         - job_id: "thr1.AAAAAGkTg_F7iwo5ThHC2w.OrGtoDmM7PM"
           index: 4
         - job_id: "thr1.AAAAAGkTg_jwDvt6sg2Ssg.lOJTbbW69LA"
           index: 5
         - job_id: "thr1.AAAAAGkThAKZSlNXismIPg.G0VPgoeznZk"
           index: 6
         - job_id: "thr1.AAAAAGkThAxrQjgfm7xu0Q.xdgZWkHdnzs"
           index: 7
         - job_id: "thr1.AAAAAGkThBbI7HDPO24akg.UjCjAEX3twg"
           index: 8
         - job_id: "thr1.AAAAAGkThCD_L4fqoPOymA.vRbCBt9mKOs"
           index: 9
         - job_id: "thr1.AAAAAGkThCsOWyC_Fkhonw.xDU7Ygo3h9k"
           index: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: |
          npm install

      - name: Esperar inicio sincronizado
        run: sleep 10

      - name: Ejecutar script
        run: node hosts.js
        env:
          JOB_ID: ${{ matrix.job_id }}
          INDEX: ${{ matrix.index }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "ðŸ‘½"
