name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGkVOGMxuROO1sOVUQ.67arMfoGJ84"
            index: 0
          - recaptcha_token: "thr1.AAAAAGkVOGo0Fg3bxgCcNQ.HMUaGFXzmNE"
            index: 1
          - recaptcha_token: "thr1.AAAAAGkVOHTCrae1ZORtTg.1dMoMA9U9eA"
            index: 2
          - recaptcha_token: "thr1.AAAAAGkVOIHIB-rx5wfY5A._HrTsqJk5aw"
            index: 3
          - recaptcha_token: "thr1.AAAAAGkVOIgR5djLLxF7mw.pvxHxu214tg"
            index: 4
          - recaptcha_token: "thr1.AAAAAGkVOJC7LIQgf57QOw.W8XnjgjsBnQ"
            index: 5
          - recaptcha_token: "thr1.AAAAAGkVOJZQbU_YzvIz1Q.MYempjSyM8o"
            index: 6
          - recaptcha_token: "thr1.AAAAAGkVOKD75KeoY0xxVQ.DnYiy0NWzuo"
            index: 7
          - recaptcha_token: "thr1.AAAAAGkVOKpVjF7I5D96dw.RSbGyhiDH3Q"
            index: 8
          - recaptcha_token: "thr1.AAAAAGkVOLPO1mSH6qPAiA.3fseaAdVZpo"
            index: 9
          - recaptcha_token: "thr1.AAAAAGkVOMEMb3-4o0UOKA.Exv-TTVNmm0"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"

