name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGkTg9m4Ff11zcG2pQ.-wv3RYFqnEs"
            index: 0
          - recaptcha_token: "thr1.AAAAAGkTg98fiQQC6Lg-2g.eGbsYtwxUYs"
            index: 1
          - recaptcha_token: "thr1.AAAAAGkTg-WVVlR-Zr99Aw.v8Uiw1INrPc"
            index: 2
          - recaptcha_token: "thr1.AAAAAGkTg-vPB78Zd7CdWA.sSLrbygGZPo"
            index: 3
          - recaptcha_token: "thr1.AAAAAGkTg_F7iwo5ThHC2w.OrGtoDmM7PM"
            index: 4
          - recaptcha_token: "thr1.AAAAAGkTg_jwDvt6sg2Ssg.lOJTbbW69LA"
            index: 5
          - recaptcha_token: "thr1.AAAAAGkThAKZSlNXismIPg.G0VPgoeznZk"
            index: 6
          - recaptcha_token: "thr1.AAAAAGkThAxrQjgfm7xu0Q.xdgZWkHdnzs"
            index: 7
          - recaptcha_token: "thr1.AAAAAGkThBbI7HDPO24akg.UjCjAEX3twg"
            index: 8
          - recaptcha_token: "thr1.AAAAAGkThCD_L4fqoPOymA.vRbCBt9mKOs"
            index: 9
          - recaptcha_token: "thr1.AAAAAGkThCsOWyC_Fkhonw.xDU7Ygo3h9k"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: ‚è≥ Esperar inicio sincronizado
        run: sleep 10

      - name: üöÄ Ejecutar host
        run: node main.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
