name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGkUt8DmT2rxXDc1YQ.2DBsUFrXKiU"
            index: 0
          - recaptcha_token: "thr1.AAAAAGkUt8kHq1xp0oqrxw.-Wb30M2LYoU"
            index: 1
          - recaptcha_token: "thr1.AAAAAGkUt9JukbY1muicLw.Nr_hYZ2uPQ0"
            index: 2
          - recaptcha_token: "thr1.AAAAAGkUt9o65o2yfxxJnw.psonnd0w2tY"
            index: 3
          - recaptcha_token: "thr1.AAAAAGkUt-I0GERfEFUazQ.QShSolP_c5A"
            index: 4
          - recaptcha_token: "thr1.AAAAAGkUt-uipWp_I9E_Nw.LYGZc7jCzvQ"
            index: 5
          - recaptcha_token: "thr1.AAAAAGkUt_gOuF3kdv66gA.vRTmX2XWpF8"
            index: 6
          - recaptcha_token: "thr1.AAAAAGkUuAYbFjF-3kCg1Q.y87bkZ6yLDo"
            index: 7
          - recaptcha_token: "thr1.AAAAAGkUuA5-SfwmX6rQPw.6omrRIt8T20"
            index: 8
          - recaptcha_token: "thr1.AAAAAGkUuBk1XySQKX4rMA.2vsyzcy1ZUA"
            index: 9
          - recaptcha_token: "thr1.AAAAAGkUuCF4WSqEh3DX7w.Gh9M9rRJrNk"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"

