name: Host - Node

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-tokens
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - job_id: "thr1.AAAAAGkAqoS-a5rpnLIsYA.Oja48Gplc54"
            index: 0
          - job_id: "thr1.AAAAAGkAqotTwMlyn6pdQQ._sjLtdYkMhY"
            index: 1
          - job_id: "thr1.AAAAAGkAqpOUFxDHd27Mcg.euj19LXuDio"
            index: 2
          - job_id: "thr1.AAAAAGkAqpuFkdsc1z41gA.ikwz08GbIqI"
            index: 3
          - job_id: "thr1.AAAAAGkAqqWX0KpfgleE7Q.S3gY7r_aY8U"
            index: 4
          - job_id: "thr1.AAAAAGkAqqtktvqd5Blztg.bUyFDkkqSf8"
            index: 5
          - job_id: "thr1.AAAAAGkAqrL2o8-8qEnzNw.kIDKyzKUOfs"
            index: 6
          - job_id: "thr1.AAAAAGkAqrvYv6L7PoDmPQ.C4P8AlkCWQY"
            index: 7
          - job_id: "thr1.AAAAAGkAqsQ_tvPklRD33A.2QqquR2UyQw"
            index: 8
          - job_id: "thr1.AAAAAGkAqstB8dQqRdlHsw.1ywfU1qlEOI"
            index: 9
          - job_id: "thr1.AAAAAGkAqteb2a9cvODM-w.GhIY7HNJ_KY"
            index: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: |
          npm install

      - name: Esperar inicio sincronizado
        run: sleep 10

      - name: Ejecutar script
        run: node hosts.js
        env:
          JOB_ID: ${{ matrix.job_id }}
          INDEX: ${{ matrix.index }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "ðŸ‘½"
