name: Hosts Node

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

concurrency:
  group: haxball-tokens
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - job_id: "thr1.AAAAAGj_5THL-j-CVQE1sQ.Jv7i249jQ_w"
            index: 0
          - job_id: "thr1.AAAAAGj_5TvgSX_AKWpuhQ.eENDZSOSw4o"
            index: 1
          - job_id: "thr1.AAAAAGj_5UNizdXdkHIjaA.D2y8TcAgrjk"
            index: 2
          - job_id: "thr1.AAAAAGj_5UvrRdlmSXwpOQ.7P8Pm8chmbs"
            index: 3
          - job_id: "thr1.AAAAAGj_5VQuvb2CoRg-og.y2CCuLYGfbo"
            index: 4
          - job_id: "thr1.AAAAAGj_5VwakwgbACZxVA.FffyfFz7ptY"
            index: 5
          - job_id: "thr1.AAAAAGj_5WcvdruSzC9c1Q.3n7_CI33a1M"
            index: 6
          - job_id: "thr1.AAAAAGj_5XFMDmx9al8-kw.KaxkFPgias8"
            index: 7
          - job_id: "thr1.AAAAAGj_5Xmd_aAtNOC4ug.-LIGAujsXEw"
            index: 8
          - job_id: "thr1.AAAAAGj_5YEjXK8ljBv4Tw.j4cRH3fndoY"
            index: 9
          - job_id: "thr1.AAAAAGj_5YiCq_lQPsVHxw.EWIpvuyRcvY"
            index: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install  

      - name: Esperar inicio sincronizado
        run: sleep 10  

      - name: Ejecutar script
        run: node hostbots.js
        env:
          JOB_ID: ${{ matrix.job_id }}
          INDEX: ${{ matrix.index }}

